### ISSUE TITLE
Events -no event messages

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#124]
When I am an user, I should not see the 'no event messages' if there's an programmes/ events going o
<img width="1256" alt="Screenshot 2023-06-03 at 9 30 22 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/b62788a0-5d67-4bfc-b03e-9e86b19ca3fd">

**Comment by shibacomputer** [comment]
This is now obsolete because we have replaced the Current Events page.
