### ISSUE TITLE
About us - hide WMA team members images

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#125]
I would like to see the WMA team members on About us as a list - with name and title only but without images

**Comment by shibacomputer** [comment]
Implemented and closed.

**Comment by ClauLung** [comment]
I cannot rearrange the order in about us page and all the WMA team members shouldn't show in WMA community page

**Comment by ClauLung** [comment]
I still cannot change the order of the team in CMS , I'd like to put Elaine --> Chloe--> Kyle--> Luna--> Hei --> Frank 
<img width="933" alt="Screenshot 2023-10-11 at 4 39 44 AM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/966082e9-c683-4359-b07b-3edf9b4acd46">
