### ISSUE TITLE
WMA Theme detailed page -WMA students winners and finalist 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#132]
For WMA students, since most of the portfolio and artworks are articles without any images, could we show theme in a list with the name of the portfolios but remove the images

**Comment by ClauLung** [comment]
we'd like to show WMA students as list of name of winner and artwork without the images , for example for opportunity:
WMA Student Winners & Finalists 
How to Tame a Tiger (to put an idea in a box in five easy steps): Lai Jamie
Cookie Cutters: Lau Hiu Ying Yoyo
What if: Lui Cheuk Yiu Dawn
Letters: Luk Ho Yan, Katie
Opportunity: Ma Nok Yee Charlotte
I See Colours: Sit Hoi Ting Chloe
Lost but not Found: To Wing Tung Anson

**Comment by shibacomputer** [comment]
This needs a final fix that I've implemented but has a weird behaviour. It will be in the next deploy.

**Comment by shibacomputer** [comment]
Had a bug with this, but it's done!
