### ISSUE TITLE
portfolio - info missing 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#136]
https://kodak.ndc.tools/portfolios/could-have-been/
when I browse the portfolio , I cant see the year of creation and the name of artist as other artworks 
<img width="696" alt="Screenshot 2023-06-06 at 4 19 01 AM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/edd4139c-8055-45f2-b830-00a0368bb4bd">

**Comment by lightlii** [comment]
https://kodak-admin.ndc.tools/admin/content-manager/collectionType/api::portfolio.portfolio/118?plugins%5Bi18n%5D%5Blocale%5D=en 

the portfolio has no associated artist...
