### ISSUE TITLE
Contact form -  translation 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#138]
when could I edit the message (in red)  in CH in CMS? 
<img width="593" alt="Screenshot 2023-06-06 at 5 22 54 AM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/ddbacdaf-82ab-4694-94ae-daf8a73567ae">

**Comment by ClauLung** [comment]
for 'submit' button, I've added global translation in CH and deployed, but still showing EN  in CH  https://kodak.ndc.tools/zh/contact/
![Screenshot 2023-09-06 at 10 03 34 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/d84bd341-fef7-4538-9921-4a99b97e0488)

**Comment by ClauLung** [comment]
EN page is showing CH submit button and vice versa 
![Screenshot 2023-09-27 at 5 32 22 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/17ae2b0f-f57f-47f7-b850-d5e51b19ee2e)
![Screenshot 2023-09-27 at 5 32 25 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/d7f6e4dd-a2d5-4754-b43a-fe4c7ffeba7f)

**Comment by shibacomputer** [comment]
Problem identified, will be fixed in next deploy
