### ISSUE TITLE
photo album- CH 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#139]
missing CH in the photo - tilte, description etc

<img width="1073" alt="Screenshot 2023-06-06 at 6 54 55 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/dd2f2560-4882-4dd2-8700-e04a76470088">
https://kodak.ndc.tools/zh/portfolios/the-flag-of-hong-kong-waving-in-the-wind/the-flag-of-hong-kong-waving-in-the-winduntitled-09-410/

**Comment by shibacomputer** [comment]
This is an issue with the CMS again, see this:
https://kodak-admin.ndc.tools/admin/content-manager/collectionType/api::artwork.artwork/414

This is an example of an artwork that doesn't have the Chinese content entered in the CMS. We can't fix this until all content is properly checked and linked.
