### ISSUE TITLE
current exhibition - in CH, showing the 'Current Exhibitions Introduction Text (No Active Exhibitions) *

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#143]
When there's a current exhibition in CH, now it's still showing the text filled in 'Current Exhibitions Introduction Text (No Active Exhibitions), which should be hided if there's something going on 

<img width="1240" alt="Screenshot 2023-06-06 at 7 20 20 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/eca19fbf-8832-4c8b-ab7a-b220bd6e63ce">

**Comment by shibacomputer** [comment]
This is obsolete due to the new behaviour for Current Exhibitions
