### ISSUE TITLE
WMA Themes - line break in content block 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#148]
For WMA theme- light theme copy, I opened new line in the CMS, but still showing wrong line alignment in the front end in both EN & CH
https://kodak-admin.ndc.tools/admin/content-manager/collectionType/api::theme.theme/2?plugins[i18n][locale]=en
<img width="788" alt="Screenshot 2023-06-07 at 4 28 43 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/4014a814-26a8-47b4-9ff7-9398c06e7f36">

**Comment by shibacomputer** [comment]
Can you revise the copy so it's exactly how you want it in the CMS?

**Comment by shibacomputer** [comment]
Looks fixed!
