### ISSUE TITLE
Themes detailed page order 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#152]
When scrolling down the theme page, the order should be Masters, Commission, WMA Open and Students. Now Commission is in the very end

**Comment by shibacomputer** [comment]
Unblocked, but I have a good idea for how to group this even more logically

**Comment by ClauLung** [comment]
for Masters, Commission, WMA Open and Students , we have Winner & finalist for each competition (data entered in CMS) , the original idea was 
option 1:
to show both winner & finalist respectively
if we dont have finalists for the year (i.e. didn't link any in CMS) , would like to hide the section 
Option 2: 
to show winner with a bigger image and finalists with small images 

would love to hear your thoughts on this or other ways to group this

**Comment by shibacomputer** [comment]
Fixed and deployed
