### ISSUE TITLE
Repeated Events. - past event & now happenings

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#153]
on this page, https://kodak.ndc.tools/events/?, some of the events shows twice - one is now happenings and one is past events while those are all past events 
<img width="721" alt="Screenshot 2023-07-20 at 11 57 49 AM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/785cd47f-4146-470d-b9a6-54cefc8785a9">
<img width="1017" alt="Screenshot 2023-07-20 at 11 57 58 AM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/bec3b41f-c83b-4e2d-bc15-9209bb6b465f">

**Comment by lightlii** [comment]
These are duplicate items in the CMS. 
![image](https://github.com/newdesigncongress/wma-hk-web/assets/32508751/3c4639b1-cb1d-4510-897f-24b43fdfb317)
![image](https://github.com/newdesigncongress/wma-hk-web/assets/32508751/e6ea499f-e713-45eb-8da1-85fa0eacc328)

Please make sure you're checking the CMS for input error before to add new issues!
