### ISSUE TITLE
Understanding HK_ responsiveness

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#156]
![Screenshot 2023-08-02 at 10 38 49 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/0dd2faef-c597-4e69-9114-340b51b056b2)

When I am on understanding HK, I want to see the paragraph alignment change according to my screen size, not open a new line in the middle of the page

**Comment by shibacomputer** [comment]
We won't extend this text any further as it breaks readability. The width here is an edge case.
