### ISSUE TITLE
Understanding HK _ hover on WMA themes

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#157]
![Screenshot 2023-08-02 at 10 54 48 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/e240b44f-b3ee-4fbc-9878-fd928bf74c71)
When I am on WMA themes on understanding HK, I want to see the hover as a transparent image over the whole section as below 
![Screenshot 2023-08-02 at 10 54 48 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/3df16d69-e835-442b-8227-0f91194f435a)
and when I hover another theme, the background transparent image will change to another theme instead of keep it there so that it wont overlap with with introductory paragraph (first image) and also it wont appear repetitively.

**Comment by shibacomputer** [comment]
Fixing this with a full width image and some colouring.

**Comment by shibacomputer** [comment]
Fixed just now
