### ISSUE TITLE
Mobile Version layout problems (Iphone 13)

### ISSUE THREAD

**Issue by WMAprogramme** [newdesigncongress/wma-hk-web#158]
![IMG_3944](https://github.com/newdesigncongress/wma-hk-web/assets/118959892/bc330402-84df-4a52-bffb-c3e6e6b048b0)

![IMG_3945](https://github.com/newdesigncongress/wma-hk-web/assets/118959892/3910b3e4-0cd7-4274-957b-5fda28ea408b)

![IMG_3946](https://github.com/newdesigncongress/wma-hk-web/assets/118959892/3b7bcd12-39e1-4e08-bcfa-1db7d7dc650b)

**Comment by shibacomputer** [comment]
Fixed!
