### ISSUE TITLE
Theme banner content box ratio 

### ISSUE THREAD

**Issue by WMAprogramme** [newdesigncongress/wma-hk-web#159]
intrinsic aspect ratio is 5:2 causing it to crop top and bottom on the image

![Screenshot 2023-08-09 at 10 14 27 AM](https://github.com/newdesigncongress/wma-hk-web/assets/118959892/fd6815a1-7886-4031-af1f-d2a72706a428)

**Comment by shibacomputer** [comment]
Fixed!
