### ISSUE TITLE
Current Exhibitions Additional Text

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#17]
Under current exhibitions page, I should be able to upload an image (key visual) with text) and links etc (listed below)

please check "F5" at https://docs.google.com/spreadsheets/d/1gqQEWke4YeGxoNJYizb2iBFgU_RtUEJndKoVU9DJUYQ/edit#gid=0

Users can check out current exhibitions including 
*Visually driven:
- key visuals  [https://wma.hk/event-inner/?programme_id=&item_id=161](https://wma.hk/event-inner/?programme_id=&item_id=1612)2
- guided tour for exhibition https://www.youtube.com/watch?v=tr_nvohZtUw (YouTube or Podcast) https://www.camera22.com/photograph/hko/
- installation shots
- recording of talks
Nice to Have[: ](https://www.instagram.com/p/CMWA0T2A9PA/)online exhibition 
- related social media post by other content creator (need to consult with Agatha and Tian)
eg.1: [https://www.instagram.com/p/CMWA0T2A9P](https://www.instagram.com/p/CMWA0T2A9PA/)A/ Being HK on CTT
eg.2[: ](https://www.instagram.com/p/CY_ZMG1vvoZ/)[https://www.instagram.com/p/CY_ZMG1vvo](https://www.instagram.com/p/CY_ZMG1vvoZ/)Z/ Chloe on WOMEN KV poster

*Words:
- curatorial statements,[https://wma.hk/zh/wei-leng-tay-solo-exhibition-abridge/](https://wma.hk/wei-leng-tay-solo-exhibition-abridge/-)
- artist's bio
- time
- venue
- register links

**Comment by shibacomputer** [comment]
Fixed with the decision around #55
