### ISSUE TITLE
current workshops page 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#19]
I should be able to upload images, bio , etc - see below 
please refer to "F3" at https://docs.google.com/spreadsheets/d/1gqQEWke4YeGxoNJYizb2iBFgU_RtUEJndKoVU9DJUYQ/edit#gid=0

Users can check out upcoming and past workshops/classes/events(boat trips)/talks
- key visual https://wma.hk/news/visual-storytelling-workshop-with-kevin-wy-lee/
- title, 
- date, 
- image, 
- venue, 
- call for application
- artist / instructor / speaker bio
[- Summary of all previous workshops/event](https://docs.google.com/spreadsheets/d/1gqQEWke4YeGxoNJYizb2iBFgU_RtUEJndKoVU9DJUYQ/edit#gid=900722150)s

**Comment by shibacomputer** [comment]
https://preview-wmahkwebmain.gatsbyjs.io/events/women-from-her-to-here/

This is from the old website. Should this be reopened?

**Comment by shibacomputer** [comment]
Need to check in on this since the fixes

**Comment by shibacomputer** [comment]
Current workshops page is obsoleted now, closed
