### ISSUE TITLE
Commission 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#22]
Commission is only to show the current commission information 

Please refer to F4 at https://docs.google.com/spreadsheets/d/1gqQEWke4YeGxoNJYizb2iBFgU_RtUEJndKoVU9DJUYQ/edit#gid=0

eg current theme - home
User can see all things about each biannual programmes, including 
-announcement
-reflections (vidoes, photos, content etc)
-Jury's comments
-events
-exhibitions (register link for public)

**Comment by lightlii** [comment]
Note for Elys: missing Events from content builder in CMS
