### ISSUE TITLE
Past exhibitions 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#57]
Where could we find the content of past exhibitions on web?

**Comment by lightlii** [comment]
to be fixed by https://github.com/newdesigncongress/wma-hk-web/issues/134

**Comment by lightlii** [comment]
users can navigate to [/events/?status=past&type=exhibition](https://kodak.ndc.tools/events/?status=past&type=exhibition), we can include this link elsewhere if we need it to be found more easily (perhaps on the current exhibitions page)
