### ISSUE TITLE
collaborators - personal page to add a 'back' button to WMA community 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#60]
When I am in one of the collaborator's page, I want to click the 'back' button at the bottom of the page to go back to WMA community to browse other collaborators, 
![image](https://user-images.githubusercontent.com/95728978/225915427-6cf4f2f4-a65e-4e55-a24e-eab9a9c2707e.png)

**Comment by shibacomputer** [comment]
This introduces some serious UX issues. If a user is on a collaborator page and have arrived there from an artist's portfolio, where does clicking the back button take them? With this feature request, it will take them to WMA Community, but they likely want to go back to the artwork page.
