### ISSUE TITLE
Collaborators without images 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#64]
For collaborators without images, would there be any replacement of the green square or could we at least hide the square?
same as WMA community pages
![image](https://user-images.githubusercontent.com/95728978/226481173-dac6beae-965c-4cbb-a3ca-d93e7537e3cf.png)
![image](https://user-images.githubusercontent.com/95728978/226481242-7c51d3dc-4e22-4044-a6a2-d96a5d38b28c.png)

**Comment by shibacomputer** [comment]
Closed as fixed - the design will look even more out of balance with partial images for collaborators.
