### ISSUE TITLE
Menu spacing 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#76]
Menu> The button between "Events" & "Understanding HK" are too close to each other. I keep clicking on the wrong one (apply to both language page)

![image](https://user-images.githubusercontent.com/95728978/227087268-e0af0cd0-7920-42df-8485-63d4af2b91da.png)

**Comment by shibacomputer** [comment]
We made some tweaks here, how does the menu feel now?
