### ISSUE TITLE
Main page - top banner not consistent in different languages

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#92]
in ENG,  Main Page > "More ->" is overlapped with the banner 
in CH, Main Page 'more' is missing and there's no hyperlinks on banner
when I link to one of the language  in featured page, it appears in another language 
![Screenshot 2023-04-12 at 12 34 52 AM](https://user-images.githubusercontent.com/95728978/231229750-3a2419e9-242a-48ae-81cc-f063610d1f63.png)

**Comment by shibacomputer** [comment]
Fixed
