### ISSUE TITLE
Events - wrong linkage

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#93]
events > it jumps to main page when I switch the language from Chinese to English (and vice versa)

**Comment by shibacomputer** [comment]
eg tested with the current event: https://kodak.ndc.tools/events/a-ride-on-our-harbour/

**Comment by ClauLung** [comment]
when I try to change the language in this page, https://kodak.ndc.tools/programmes/ , it jumps to homepage. https://kodak.ndc.tools/zh/programmes/ this one as well
