### ISSUE TITLE
Current events 

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#94]
the Key visual should come before the event details or displayed next to the event details

**Comment by ClauLung** [comment]
I would like to see the Key visual first, then I can read the programmes details 
![A-Ride-on-Our-Harbour-WMA-hk](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/c642cdd2-029a-42f1-9744-fc2bcdc2e149)

**Comment by ClauLung** [comment]
Not yet fixed, still not see the key visual showing at the top of the page 
![image](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/1fe061d8-7410-48e3-859b-1b9afdab54b7)

**Comment by lightlii** [comment]
Sorry, I'd understood you meant on a different page. This should be resolved now (pending new build)

**Comment by lightlii** [comment]
went ahead and fixed #105 whilst I was there too

**Comment by ClauLung** [comment]
Chinese page hasn't fixed. https://kodak.ndc.tools/zh/programmes/
<img width="1420" alt="Screenshot 2023-09-02 at 1 47 18 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/da04adc2-0c0c-4a90-a679-4bb68828bdcb">

**Comment by shibacomputer** [comment]
This got blocked by a bad deploy, this was my fault. It's fixed!
