### ISSUE TITLE
Current Exhibitions

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#95]
As a user, I would know to see the key visual on current exhibitions

**Comment by shibacomputer** [comment]
Obsolete due to the new current exhibition functionality

**Comment by ClauLung** [comment]
for current exhibition in CH, it doesn't show 'location' as EN, but added in global translation in CMS 
<img width="1329" alt="Screenshot 2023-10-19 at 11 28 53 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/59091337-4315-4c72-bf8c-33ddeff3bbc0">
doesn't 'location 
<img width="601" alt="Screenshot 2023-10-19 at 11 30 10 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/369beede-b9fd-44e5-9f6d-075cf045ca9a">
<img width="1108" alt="Screenshot 2023-10-19 at 11 31 09 PM" src="https://github.com/newdesigncongress/wma-hk-web/assets/95728978/586ffe0e-29b1-4993-9ddf-44a66e02db0d">
